### ISSUE TITLE
Spartahack website

### ISSUE THREAD

**Issue by SwapnikKatkoori** [SpartaHack/SpartaHackVI-Website#6]
Do you guys need any help on the website? I would love to help anyway I can if you have any tasks that need doing.

**Comment by jarek-t** [comment]
Yeah actually that would be awesome. We're working on making sure the authentication & everything works so with that we're quite a few undocumented conversations deep, but we need to finish making FAQs work well then have a sponsor section on the site. That stuff is gonna be API driven & pretty easy to deal with. FAQS pretty much has the usability JS written, but it might need to be tweaked as the SCSS is completed then we have nothing for sponsors except API documentation & a sample JSON.

What's your email?

**Comment by SwapnikKatkoori** [comment]
Awesome, sounds good.
katkoor2@msu.edu

**Comment by jarek-t** [comment]
I just invited you to my Todoist list with what I need to complete. If you want to look at that & do what you can/have time for, we can merge stuff in & add you to repos/comms once I'm back in contact with one of the co-directors.

Thanks again/LMK if you have any questions!
